[Service]
ExecStart=
ExecStart=docker run --rm --runtime nvidia --cap-add SYS_ADMIN -p 8033:8080 \
 -v /home/jim/models:/models \
 -v /home/jim/llama-swap/config.yaml:/app/config.yaml \
 ghcr.io/mostlygeek/llama-swap:cuda
